<a href="https://colab.research.google.com/github/nastyamahnevitch/data-processing-technologies1/blob/main/01_numpy_%D0%94%D0%9F%D0%9823_1_%D0%9C%D0%B0%D1%85%D0%BD%D0%B5%D0%B2%D0%B8%D1%87_%D0%90%D0%BD%D0%B0%D1%81%D1%82%D0%B0%D1%81%D0%B8%D1%8F.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy

Материалы:
* Макрушин С.В. "Лекция 1: Библиотека Numpy"
* https://numpy.org/doc/stable/user/index.html
* https://numpy.org/doc/stable/reference/index.html

## Задачи для совместного разбора

1. Сгенерировать двухмерный массив `arr` размерности (4, 7), состоящий из случайных действительных чисел, равномерно распределенных в диапазоне от 0 до 20. Нормализовать значения массива с помощью преобразования вида  $𝑎𝑥+𝑏$  так, что после нормализации максимальный элемент масcива будет равен 1.0, минимальный 0.0

In [1]:
import numpy as np
data = np.random.uniform(0, 20, size = (4, 7))
print(data)
(data-np.min(data))/(np.max(data)-np.min(data))

[[ 1.9246505  12.54421802 18.31845203  6.36329746  9.82125426 10.37005363
  12.27926791]
 [ 0.80469595  2.16080943  9.84288531 15.31478708  3.36853371 10.79625225
   0.42568296]
 [15.25743663  0.7517413   2.84634774  5.5627373   3.67822104 13.8030396
   2.08705817]
 [ 5.23958208 14.55392283 10.08294552  0.02769256 11.2430547  14.10099666
  10.11587245]]


array([[0.10371127, 0.68430868, 1.        , 0.34638282, 0.53543767,
        0.56544186, 0.66982322],
       [0.04248065, 0.11662265, 0.5366203 , 0.83578238, 0.18265186,
        0.58874317, 0.0217591 ],
       [0.83264689, 0.03958549, 0.15410269, 0.30261427, 0.19958321,
        0.7531315 , 0.11259049],
       [0.28494659, 0.7941841 , 0.54974497, 0.        , 0.61317094,
        0.76942153, 0.55154516]])

In [ ]:
np.random.randint(0, 20, size = (4, 7))

array([[10,  5,  4,  8,  4, 15, 15],
       [17, 16,  9, 15,  7,  7,  5],
       [18,  5, 19,  3,  8, 12,  3],
       [ 2, 14, 17, 17,  7, 18, 10]])

2. Создать матрицу 8 на 10 из случайных целых (используя модуль `numpy.random`) чисел из диапозона от 0 до 10 и найти в ней строку (ее индекс и вывести саму строку), в которой сумма значений минимальна.

In [ ]:
np.random.randint(0, 10, size = (8, 10))
arr = np.random.randint(0, 10, size = (8, 10))
print(arr)
print("Row Index",np.argmin(np.sum(arr, axis=1)))
arr[np.argmin(np.sum(arr, axis=1))]

[[5 7 3 0 6 7 2 0 7 3]
 [0 8 5 4 2 7 9 5 4 8]
 [5 4 8 0 3 4 0 1 5 0]
 [9 6 6 6 6 0 9 9 3 5]
 [0 1 8 9 5 7 3 7 7 6]
 [7 1 3 8 5 1 6 5 9 7]
 [3 6 1 9 9 4 7 1 7 8]
 [8 5 9 8 0 6 1 7 7 4]]
Row Index 2


array([5, 4, 8, 0, 3, 4, 0, 1, 5, 0])

3. Найти евклидово расстояние между двумя одномерными векторами одинаковой размерности.

In [ ]:
import matplotlib.pyplot as pl
from mpl_toolkits.mplot3d import Axes3D

In [ ]:
point_1 = np.random.randint(0, 20, size=5)
point_2 = np.random.randint(0, 20, size=5)
print(point_1)
print(point_2)
#first way
square = np.square(point_1 - point_2)
sum_square = np.sum(square)
print(np.sqrt(sum_square))
#second way
distance = np.linalg.norm(point_1-point_2)
print(distance)

[ 5 15 11 12  0]
[16  0  7 15 18]
26.362852652928137
26.362852652928137


4. Решить матричное уравнение `A*X*B=-C` - найти матрицу `X`. Где `A = [[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]]`, `B=[[3, -1], [2, 1]]`, `C=[[7, 21], [11, 8], [8, 4]]`.

In [ ]:
a = np.array([[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]])
b = np.array([[3, -1], [2, 1]])
c = np.array([[7, 21], [11, 8], [8, 4]])
#решение: x = a^-1*(-c)*b^-1

x0 = np.matmul(np.linalg.inv(a),(-c))
print(x0)
x =  np.matmul(x0,np.linalg.inv(b))
print(x)

[[ 3. -1.]
 [-4.  3.]
 [ 1. -7.]]
[[ 1.00000000e+00  5.32907052e-16]
 [-2.00000000e+00  1.00000000e+00]
 [ 3.00000000e+00 -4.00000000e+00]]


## Лабораторная работа №1

Замечание: при решении данных задач не подразумевается использования циклов или генераторов Python, если в задании не сказано обратного. Решение должно опираться на использования функционала библиотеки `numpy`.

1. Файл `minutes_n_ingredients.csv` содержит информацию об идентификаторе рецепта, времени его выполнения в минутах и количестве необходимых ингредиентов. Считайте данные из этого файла в виде массива `numpy` типа `int32`, используя `np.loadtxt`. Выведите на экран первые 5 строк массива.

In [2]:
data = np.loadtxt("minutes_n_ingredients.csv", delimiter=',', skiprows=1, dtype=np.int32)
# first 5 rows
print(data[0:5, :])

[[127244     60     16]
 [ 23891     25      7]
 [ 94746     10      6]
 [ 67660      5      6]
 [157911     60     14]]


2. Вычислите среднее значение, минимум, максимум и медиану по каждому из столбцов, кроме первого.

In [ ]:
#делаем срез массива, извлекаем все кроме первого массива
sliced = data[:,1:]
# находим среднее по столбцам среза
print(np.mean(sliced,axis=0))
# находим минимум по столбцам среза
print(np.min(sliced, axis=0))
# находим максимум по столбцам среза
print(np.max(sliced, axis=0))
# находим медиану по столбцам среза
print(np.median(sliced, axis=0))

[2.16010017e+04 9.05528000e+00]
[0 1]
[2147483647         39]
[40.  9.]


3. Ограничьте сверху значения продолжительности выполнения рецепта значением квантиля $q_{0.75}$.

In [ ]:
np.clip(data[:, 1],0,np.quantile(data[:, 1],0.75,method='higher'))

array([60, 25, 10, ..., 65,  5, 65], dtype=int32)

4. Посчитайте, для скольких рецептов указана продолжительность, равная нулю. Замените для таких строк значение в данном столбце на 1.

In [ ]:
print(np.count_nonzero (data[:, 1] == 0))
np.place(data, data==0, 1)

479


5. Посчитайте, сколько уникальных рецептов находится в датасете.

In [ ]:
#уникальные рецепты - это рецепты, у которых не повторяются минуты и количество ингредиентов
len(np.unique(sliced, axis=0))

4183

6. Сколько и каких различных значений кол-ва ингредиентов присутвует в рецептах из датасета?

In [ ]:
print(np.unique(data[:, 2], axis=0))
print(np.unique(data[:, 2], axis=0).size)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 37 39]
37


7. Создайте версию массива, содержащую информацию только о рецептах, состоящих не более чем из 5 ингредиентов.

In [ ]:
data2 = data[np.where(data[:, 2] <= 5)]
print(data2)

[[446597     15      5]
 [204134      5      3]
 [ 25623      6      4]
 ...
 [ 52088     60      5]
 [128811     15      4]
 [370915      5      4]]


8. Для каждого рецепта посчитайте, сколько в среднем ингредиентов приходится на одну минуту рецепта. Найдите максимальное значение этой величины для всего датасета

In [ ]:
data3 = data[:, 2] / data[:, 1]
print(np.max(data3))

24.0


9. Вычислите среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью

In [ ]:
top_100 = data[data[:,0].argsort()][-100:]
average_ingredients = np.mean(top_100[:,1])
average_ingredients


156.62

10. Выберите случайным образом и выведите информацию о 10 различных рецептах

In [ ]:
import random
rand_10 = random.choices(data,  k = 10 )
rand_10

[array([392746,     20,     10], dtype=int32),
 array([60839,    25,     7], dtype=int32),
 array([527481,     15,     12], dtype=int32),
 array([132040,     15,      7], dtype=int32),
 array([293158,     95,     13], dtype=int32),
 array([168413,     15,      8], dtype=int32),
 array([348562,     40,     12], dtype=int32),
 array([355981,    120,      3], dtype=int32),
 array([58764,    40,     9], dtype=int32),
 array([64377,    40,     8], dtype=int32)]

11. Выведите процент рецептов, кол-во ингредиентов в которых меньше среднего.

In [10]:
ingr = data[:, 2]
ingr_mean = np.mean(ingr)
less_mean = ingr < ingr_mean
print((ingr[less_mean].size / ingr.size) *100)

58.802


12. Назовем "простым" такой рецепт, длительность выполнения которого не больше 20 минут и кол-во ингредиентов в котором не больше 5. Создайте версию датасета с дополнительным столбцом, значениями которого являются 1, если рецепт простой, и 0 в противном случае.

In [46]:
is_simple = np.where((data[:, 1] < 20) & (data[:, 2] < 5), 1, 0)
is_simple.shape = 1, -1
new_array = np.append(data.copy(), is_simple.T, axis= 1)

[[127244     60     16      0]
 [ 23891     25      7      0]
 [ 94746     10      6      0]
 [ 67660      5      6      0]
 [157911     60     14      0]
 [152828     40      7      0]
 [ 33941     18      9      0]
 [446597     15      5      0]
 [366174      7      9      0]
 [ 74205     20      7      0]
 [504666     65     20      0]
 [ 81006     12      7      0]
 [280968     85     11      0]
 [204134      5      3      1]
 [ 18593     35      7      0]
 [ 25623      6      4      1]
 [ 65559     24     14      0]
 [ 99836    180      7      0]
 [ 87775     80     13      0]
 [425704     40     12      0]]


13. Выведите процент "простых" рецептов в датасете

In [49]:
simple = (data[:, 1] < 20) & (data[:, 2] < 5)
data5 = new_array[:, 3]
print((data5[simple].size / data5.size)*100)

5.093


14. Разделим рецепты на группы по следующему правилу. Назовем рецепты короткими, если их продолжительность составляет менее 10 минут; стандартными, если их продолжительность составляет более 10, но менее 20 минут; и длинными, если их продолжительность составляет не менее 20 минут. Создайте трехмерный массив, где нулевая ось отвечает за номер группы (короткий, стандартный или длинный рецепт), первая ось - за сам рецепт и вторая ось - за характеристики рецепта. Выберите максимальное количество рецептов из каждой группы таким образом, чтобы было возможно сформировать трехмерный массив. Выведите форму полученного массива.